### ISSUE TITLE
separators needed for multiple filter rules

### ISSUE THREAD

**Issue by peller** [jupyter-incubator/declarativewidgets_explorer#5]
maybe a horizontal rule or even-odd background colors?

**Comment by dalogsdon** [comment]
Even-odd colors doesn't look like it would work since that would be CSS on the query widget, but the query widget is placed in a card in the explorer that has its own padding, so we would have to ensure the contents fill the full horizontal space, which would be a special case for the query widget... too complex I think.

Horizontal rule seems a bit old school, so I'll first try to adjust the spacing, both the height of the inputs themselves (in itself a larger issue since the controls take up a lot of vertical space) as well as adding some space between the filters. This combined with the already existing delete icons beside the bottom input of each filter should help visually separate the filters.

**Comment by dalogsdon** [comment]
It's a bit tricky to adjust the height of the paper dropdown menus since they don't use good CSS variables to make it easy. I added some spacing in #13, so we can see if that is sufficient for this. I would like things to get more compact in general, though, so the UI isn't sprawling.

**Comment by peller** [comment]
need to do the same for aggregators
