### ISSUE TITLE
[Feature request] Is there a way to order the data in charts?

### ISSUE THREAD

**Issue by rs2** [jupyter-incubator/declarativewidgets_explorer#75]
It would be very useful to e.g. re-rank the bar plot by the size of the bar, desc/asc.

**Comment by peller** [comment]
we should support sorting on the kernel using `urth-core-query-sort`  We could sort unsorted dataframe results on the client too, but that might be confusing.

**Comment by dalogsdon** [comment]
The sort should be done server-side using `urth-core-query-sort`. Sorting client-side would be misleading since we have a limit. I presume the limit is applied after all queries, so the sort would be placed as the last query? This may make sense since the `<urth-core-query-sort>` element will follow all other `<urth-core-query-*>` elements?
